steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud run deploy fastapi-ml-recommender \
          --source . \
          --region us-central1 \
          --platform=managed \
          --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 900s
